server:
  port: 8010
spring:
  application:
    name: lab-4-eureka-server
---
spring:
  profiles: primary
server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8012/eureka/,http://localhost:8013/eureka/
---
spring:
  profiles: secondary
server:
  port: 8012
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8013/eureka/
---
spring:
  profiles: tertiary
server:
  port: 8013
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8012/eureka/,http://localhost:8011/eureka/