server:
  port: 8020
spring:
  application:
    name: lab-6-sentence
  config:
    import: configserver:http://localhost:8001
management:
  endpoints:
    web:
      exposure:
        include:
          - 'hystrix.stream'
